export declare const config: Readonly<{
    NODE_ENV: string;
    PORT: number;
    HOST: string;
    CORS_ORIGINS: string;
    DATABASE_URL: string;
    REDIS_URL: string;
    JWT_ISSUER: string;
    JWT_AUDIENCE: string;
    JWT_ACCESS_EXPIRY: string;
    JWT_REFRESH_EXPIRY: string;
    JWT_PRIVATE_KEY: string;
    JWT_PUBLIC_KEY: string;
    STRIPE_SECRET_KEY: string;
    STRIPE_PUBLISHABLE_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
    STRIPE_PRICE_STARTER: string;
    STRIPE_PRICE_PROFESSIONAL: string;
    STRIPE_PRICE_ENTERPRISE: string;
    MAILJET_API_KEY: string;
    MAILJET_SECRET_KEY: string;
    MAILJET_FROM_EMAIL: string;
    MAILJET_FROM_NAME: string;
    TWILIO_ACCOUNT_SID: string;
    TWILIO_AUTH_TOKEN: string;
    TWILIO_PHONE_NUMBER: string;
    TWILIO_VERIFY_SERVICE_SID: string;
    SENTRY_DSN: string;
    SENTRY_ENVIRONMENT: string;
    S3_BUCKET: string;
    S3_REGION: string;
    S3_ACCESS_KEY_ID: string;
    S3_SECRET_ACCESS_KEY: string;
    ENABLE_OAUTH: boolean;
    ENABLE_2FA: boolean;
    ENABLE_MAGIC_LINKS: boolean;
    OPENKJ_LEGACY_API_PREFIX: string;
}>;
export declare const isDevelopment: boolean;
export declare const isProduction: boolean;
export declare const isTest: boolean;
//# sourceMappingURL=index.d.ts.map